In [0]:
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import VotingClassifier
from sklearn import metrics

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
iris = datasets.load_iris()

In [3]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [36]:
x = iris.data
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [0]:
y = iris.target

In [30]:
x.shape, y.shape

((150, 4), (150,))

In [0]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.4)

In [32]:
rdClf = RandomForestClassifier()
rdClf.fit(xtrain,ytrain)
rResult = rdClf.predict(xtest)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [27]:
rResult

array([1, 1, 1, 2, 2, 1, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 1, 0, 0,
       1, 2, 0, 1, 1, 1, 0, 2, 1, 0, 0, 2, 0, 1, 2, 1, 2, 2, 2, 0, 1, 1,
       0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0])

In [56]:
t = np.array([[1,2,3,4]])
rdClf.predict(t)

array([2])

In [60]:
metrics.accuracy_score(ytest,rResult),metrics.precision_score(ytest,rResult,average=None),metrics.recall_score(ytest,rResult,average=None)

(0.95,
 array([1.        , 0.88235294, 0.95454545]),
 array([1.        , 0.9375    , 0.91304348]))

실습

In [61]:
from google.colab import drive

drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [68]:
data = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/data/Diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [71]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]
x.shape,y.shape

((768, 8), (768,))

In [0]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=0)

In [0]:
lr = LogisticRegression()
knn = KNeighborsClassifier()
dt = DecisionTreeClassifier()

classifiers = [('LR',lr),("KNN",knn),("DT",dt)]

In [89]:
for clf_namem,clf in classifiers:
  clf.fit(xtrain,ytrain)
  rResult = clf.predict(xtest)
  accuracy = metrics.accuracy_score(ytest, rResult)
  print(accuracy)

0.7835497835497836
0.7489177489177489
0.70995670995671


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [91]:
from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators=classifiers)
vc.fit(xtrain,ytrain)
rResult2 = vc.predict(xtest)
accuracy2 = metrics.accuracy_score(ytest, rResult2)
print(accuracy2)

0.7835497835497836


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
