- 설치 - 아나콘다 프롬프트

```
conda create --name tensorflow python=3.7

activate tensorflow

conda install jupyter

```

- python에서 tensorflow 사용(jupyter notebook-tensorflow)

```
import tensorflow as tf

hello = tf.constant('Hello,Tensorflow')

sess = tf.Session()

print(sess.run(hello))
```

In [5]:
import tensorflow as tf

hello = tf.constant('Hello,Tensorflow')

sess = tf.Session()

print(sess.run(hello))

b'Hello,Tensorflow'


In [0]:
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

In [7]:
result = tf.multiply(x1,x2)
print(result)

Tensor("Mul:0", shape=(4,), dtype=int32)


In [8]:
sess.run(result)

array([ 5, 12, 21, 32], dtype=int32)

In [9]:
import numpy as np
test1 = np.array([1.5,1,5.0,23.0])
test1

array([ 1.5,  1. ,  5. , 23. ])

In [0]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [0]:
np.random.seed(101)
tf.set_random_seed(101)

In [0]:
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a*b

In [13]:
c

<tf.Tensor 'mul_1:0' shape=() dtype=float32>

In [32]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!wget https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta/+build/15331130/+files/google-drive-ocamlfuse_0.7.0-0ubuntu1_amd64.deb
!dpkg -i google-drive-ocamlfuse_0.7.0-0ubuntu1_amd64.deb
!apt-get install -f
!apt-get -y install -qq fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

E: Package 'python-software-properties' has no installation candidate
--2019-04-09 05:56:28--  https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta/+build/15331130/+files/google-drive-ocamlfuse_0.7.0-0ubuntu1_amd64.deb
Resolving launchpad.net (launchpad.net)... 91.189.89.223, 91.189.89.222, 2001:67c:1560:8003::8004, ...
Connecting to launchpad.net (launchpad.net)|91.189.89.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-09 05:56:29 ERROR 404: Not Found.

dpkg: error: cannot access archive 'google-drive-ocamlfuse_0.7.0-0ubuntu1_amd64.deb': No such file or directory
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-410
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
··········
/bin/bash: google-drive-ocamlfuse: command not found


In [10]:
  LOG_DIR = 'drive/data/tb_logs'
	
  !wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  !unzip ngrok-stable-linux-amd64.zip
	
  import os
  if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)
	  
  get_ipython().system_raw(
      'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
      .format(LOG_DIR))
	
  get_ipython().system_raw('./ngrok http 6006 &')
	
  !curl -s http://localhost:4040/api/tunnels | python3 -c \
      "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

--2019-04-09 05:34:36--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
Resolving bin.equinox.io (bin.equinox.io)... 52.87.35.92, 52.203.66.95, 52.86.186.182, ...
Connecting to bin.equinox.io (bin.equinox.io)|52.87.35.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14977695 (14M) [application/octet-stream]
Saving to: ‘ngrok-stable-linux-amd64.zip.2’

ngrok-stable-linux- 100%[===================>]  14.28M  17.9MB/s    in 0.8s    

2019-04-09 05:34:37 (17.9 MB/s) - ‘ngrok-stable-linux-amd64.zip.2’ saved [14977695/14977695]

Archive:  ngrok-stable-linux-amd64.zip
replace ngrok? [y]es, [n]o, [A]ll, [N]one, [r]ename: Y
  inflating: ngrok                   
http://29e3d6f4.ngrok.io


In [3]:
LOG_DIR = 'tb_logs'

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

import os
if not os.path.exists(LOG_DIR):
  os.makedirs(LOG_DIR)

get_ipython().system_raw(
    'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
    .format(LOG_DIR))

get_ipython().system_raw('./ngrok http 6006 &')

!curl -s http://localhost:4040/api/tunnels | python3 -c "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

--2019-04-09 05:44:51--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
Resolving bin.equinox.io (bin.equinox.io)... 34.206.36.121, 52.86.186.182, 34.206.9.96, ...
Connecting to bin.equinox.io (bin.equinox.io)|34.206.36.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14977695 (14M) [application/octet-stream]
Saving to: ‘ngrok-stable-linux-amd64.zip.1’

ngrok-stable-linux- 100%[===================>]  14.28M  7.01MB/s    in 2.0s    

2019-04-09 05:44:54 (7.01 MB/s) - ‘ngrok-stable-linux-amd64.zip.1’ saved [14977695/14977695]

Archive:  ngrok-stable-linux-amd64.zip
replace ngrok? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ngrok                   
https://f13e7e3d.ngrok.io


In [19]:
from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
sess = tf.Session()
writer = tf.summary.FileWriter('/content/gdrive/My Drive/Colab Notebooks/ASD',sess.graph)

In [23]:
!pip install tensorboardcolab

In [0]:
from keras.callbacks import TensorBoard
from google.colab import files

In [0]:
tensorboard = TensorBoard(log_dir=LOG_DIR, histogram_freq=0, write_graph=True, write_images=True)

In [31]:
%tensorboard --logdir /content/gdrive/My Drive/Colab Notebooks/ASD

UsageError: Line magic function `%tensorboard` not found.


In [0]:
output_c = sess.run(c)

In [16]:
output_c

30.0

In [0]:
a1 = tf.placeholder(tf.float32)
b1 = tf.placeholder(tf.float32)
c1 = a1 * b1
output_c1 = sess.run(c1,{a1:[1,2],b1:[2,4]})

In [18]:
output_c1

array([2., 8.], dtype=float32)

In [19]:
# Variable
d1 = tf.Variable([0.7],dtype=tf.float32)

Instructions for updating:
Colocations handled automatically by placer.


In [20]:
d1

<tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>